import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handlePage = (e: any) => {
    console.log(e);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Burak Ozcelik CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div onClick={handlePage} className={styles.middleScreen}>
        Personal Info
      </div>
      <div className={styles.middleScreen}>Education</div>
      <div className={styles.middleScreen}>Experiences</div>
      <div className={styles.middleScreen}>Projects</div>
      <div className={styles.middleScreen}>General Info</div>
    </div>
  );
}
