import Head from "next/head";
import { useRouter } from "next/router";

import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  const handlePage = (e: any) => {
    router.push("/" + e);

    console.log(e);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Burak Ozcelik CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div
        onClick={() => handlePage("personalinfo")}
        className={styles.middleScreen}
      >
        Personal Info
      </div>
      <div
        onClick={() => handlePage("education")}
        className={styles.middleScreen}
      >
        Education
      </div>
      <div
        onClick={() => handlePage("experience")}
        className={styles.middleScreen}
      >
        Experiences
      </div>
      <div
        onClick={() => handlePage("projects")}
        className={styles.middleScreen}
      >
        Projects
      </div>
      <div
        onClick={() => handlePage("generalinfo")}
        className={styles.middleScreen}
      >
        General Info
      </div>
    </div>
  );
}
